export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_START_STATION = 'SET_START_STATION';
export const SET_END_STATION = 'SET_END_STATION';
export const SET_TRANSPORT_RESULTS = 'SET_TRANSPORT_RESULTS';